### ISSUE TITLE
CentOS 6 foi descontinuado

### ISSUE THREAD

**Issue by D-BlindSide** [spbgovbr/sei-docker-antigo#1]
Olá! Como faremos para construir os containers do sei agora que os repositórios do CentOS foram descontinuados?
Será que não seria o caso de utilizar os oficiais do PHP?

Segue o log ao tentar construir o container APP:

```$  docker build . -t sei
Sending build context to Docker daemon  3.844MB
Step 1/28 : FROM centos:6.7
 ---> 9f1de3c6ad53
Step 2/28 : ENV SEI_HOST_URL localhost
 ---> Running in 59d182252475
Removing intermediate container 59d182252475
 ---> cda3b04595b9
Step 3/28 : ENV SEI_ORGAO MP
 ---> Running in e90e48a097db
Removing intermediate container e90e48a097db
 ---> 5d710dcbf3a9
Step 4/28 : COPY files/install.sh /install.sh
 ---> 80405516954b
Step 5/28 : COPY files/msttcore-fonts-2.0-3.noarch.rpm /usr/local/bin/
 ---> 7855eac10f62
Step 6/28 : RUN bash /install.sh
 ---> Running in 7b50611a7414
Loaded plugins: fastestmirror
Cleaning repos: base extras updates
Cleaning up Everything
Loaded plugins: fastestmirror
Setting up Update Process
Determining fastest mirrors
Error: Cannot find a valid baseurl for repo: base
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
The command '/bin/sh -c bash /install.sh' returned a non-zero code: 1```

**Comment by marlinhares** [comment]
Olá @D-BlindSide ,

desculpe a demora na resposta vou tentar focar mais aqui. 
Seguinte para o Centos6, vc pode apontar para algum repositório alternativo que vai funcionar de boa. Eu não posso indicar ele por aqui pois é alternativo, então as verificaçoes de segurança eu não tenho como garantir.

Em tempo esse projeto aqui sofrerá uma reformulação a partir de hoje.

Iremos criar uma stack completa totalmente customizável para instalação completa do SEI com todos os componentes necessários usando docker.

Inicialmente será focado em ambiente de DTH e usando o SEI4. A medida que a comunidade for alinhando poderemos evoluir para algo mais próximo de prod. Falo mais próximo pq produção a instalação do SEI é apenas uma ponta do iceberg de cuidados necessários.

Stay tunned
